eshoppieapp/urls.py
from django.urls import path
from . import views
app_name='eshopapp'
urlpatterns = [
    #path('',views.index,name='index' ),
    path('admino/',views.admino,name='admino' ),
    path('category/',views.category,name='category' ),
    path('seller/',views.seller,name='seller' ),
    path('product/',views.product,name='product' ),
    path('addcart/<int:pid>',views.addcart,name='addcart' ),
    #path('buyprod/',views.buyprod,name='buyprod' ),
    path('',views.register,name='register' ),
    path('login/',views.login,name='login' ),
    #path('findprod/<str:canm>/',views.findprod,name='findprod' ),
    
   # path('register/',views.register,name='register' ),
    path('dellogininfo/',views.dellogininfo,name='dellogininfo'),
   # path('adminsession/',views.adminsession,name='adminsession'),
   path('cartdisplay/',views.cartdisplay,name='cartdisplay'),
   path('checkout/<int:pid>/',views.checkoutedit,name='checkout'),

]

onlinecart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('django.contrib.auth.urls')),
    path('', include('eshoppieapp.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

eshoppieapp/models.py
from django.db import models

# Create your models here.
class AdminTable(models.Model):
    username=models.CharField(max_length=20)
    password=models.IntegerField()

class category_details(models.Model):
    category_ID=models.AutoField(primary_key=True)
    category_name=models.CharField(max_length=20)
    category_description=models.CharField(max_length=30)

    def __str__(self):
        return self.category_name



class user(models.Model):
    user_id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=20)
    username=models.CharField(max_length=10)
    date_of_birth=models.DateTimeField()
    adress=models.CharField(max_length=30)
    email=models.CharField(max_length=20)
    phone_number=models.IntegerField()
    password=models.CharField(max_length=10)
    

    
class SellerTable(models.Model):
    Seller_ID=models.AutoField(primary_key=True)
    sellername=models.CharField(max_length=20,db_column="sname")
    adress=models.CharField(max_length=20)
    email=models.CharField(max_length=20)
    password=models.CharField(max_length=10)
    phone_number=models.IntegerField()

    def __str__(self):
        return self.sellername
    class Meta:
        db_table="tb_seler"
   


class ProductTable(models.Model):
    Product_ID=models.AutoField(primary_key=True)
    quantity=models.IntegerField(default=0,null=True) 
    Product_name=models.CharField(max_length=20)
    product_image= models.ImageField(upload_to='product_image/',null=True,blank=True)
    price=models.IntegerField()
    category_ID=models.ForeignKey(category_details, on_delete=models.CASCADE)
    Seller_ID=models.ForeignKey(SellerTable,on_delete=models.CASCADE)
    
    @property
    def imageURL(self):
		    try:
			    url = self.product_image.url
		    except:
			    url = ''
		    return url



class cart(models.Model):
    Product_ID=models.ForeignKey(ProductTable,on_delete=models.CASCADE)        
    user_id=models.ForeignKey(user,on_delete=models.CASCADE,null=True)
    Quantity=models.IntegerField(default=0)
class orders(models.Model):
    user_ID=models.ForeignKey(user,on_delete=models.CASCADE)
    Product_ID=models.ForeignKey(ProductTable,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    TotalPrice=models.IntegerField()
    Order_date=models.DateTimeField()
    Expected_Delivery=models.DateTimeField()
    
   

eshoppieapp/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class indexform(forms.ModelForm):
    class Meta:
        model=AdminTable
        fields=("username","password")
        labels={
            'username':'Enter username',
            'password':'password',
        }
        widgets={
            'password':forms.PasswordInput(),
        }
class catform(forms.ModelForm):
    class Meta:
        model=category_details
        fields="__all__"

class sellerform(forms.ModelForm):
    class Meta:
        model=SellerTable
        fields=('sellername', 'adress', 'email','password','phone_number',)
        labels={
            'sellername':'sellername','adress':'Adress','email':'Email','password':'password', 'phone_number':'phone'
        }
        widgets={
            'adress':forms.Textarea(attrs={'rows':8,'cols':18}),
            'email':forms.EmailInput(),
            'password':forms.PasswordInput(),
        }
class productform(forms.ModelForm):
    class Meta:
        model=ProductTable
        fields=("__all__")
        labels={
            'category_ID':'Category','Seller_ID':'seller'
        }
class userform(forms.ModelForm):
    class Meta:
        model=user
        fields="__all__"

        widgets={
             'email':forms.EmailInput(),
            'password':forms.PasswordInput(),
            'confirm_password':forms.PasswordInput(),
            'adress':forms.Textarea(attrs={'rows':8,'cols':18}),
            
        }
'''class createuserform(UserCreationForm):
    class Meta:
        model=user
        #fields=['Username','email','password1','password2']'''

class registerform(forms.ModelForm):
    class Meta:
        model=user
        fields="__all__" 
        widgets={
            'email':forms.EmailInput(),
            'password':forms.PasswordInput(),
           
            'adress':forms.Textarea(attrs={'rows':8,'cols':18}),
            
        }

        def clean(self):
            cleaned_data=super().clean()
            valpwd=self.cleaned_data['password']
            valrpwd=self.cleaned_data['confirm_password']
            if valpwd !=valrpwd:
                raise forms.ValidationError("Password does not match")
class loginform(forms.ModelForm):
    class Meta:
        model=user
        fields=('username','password')
        widgets={
            'password':forms.PasswordInput(),
        }
class buyprodform(forms.ModelForm):
    class Meta:
        model=ProductTable
        fields=('category_ID',)
        labels={
            'category_ID':'Category',
        }
class cartform(forms.ModelForm):
    class Meta:
        models=cart
        fields="__all__"

class orderform(forms.ModelForm):
    class Meta:
        model=orders
        exclude=('user_ID','Product_ID')
      
        

eshoppieapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import *
from .models import *
from django.contrib.auth.forms import UserCreationForm
from datetime import date,timedelta

# Create your views here.
def index(request):
    ind=indexform()
    return render(request,'index.html',{'ind':ind})
def admino(request):
    products=ProductTable.objects.all()
    #if request.method=="POST":      
        #products=ProductTable.objects.all()
        #return render(request,'admin.html',{'products':products,})

    return render(request,'admin.html',{'products':products,})
    
def category(request):
    cat=catform()
    if request.method=='POST':
        cat=catform(request.POST)
        if cat.is_valid():
            cname=cat.cleaned_data['category_name']
            cdescription=cat.cleaned_data['category_description']
            res=category_details(category_name=cname,category_description=cdescription)
            res.save()
            msg="category added"
        return render(request,'category.html',{'cat':cat,'msg':msg})
    
    return render(request,'category.html',{'cat':cat})

def seller(request):
    sel=sellerform()
    if request.method=="POST":
        sel=sellerform(request.POST)
        if sel.is_valid():
            sname=sel.cleaned_data['sellername']
            sadress=sel.cleaned_data['adress']
            semail=sel.cleaned_data['email']
            spassword=sel.cleaned_data['password']
            sphone=sel.cleaned_data['phone_number']
            res=SellerTable(sellername=sname,adress=sadress,email=semail,password=spassword,phone_number=sphone)
            res.save()
            msg="seller added"
        return render(request,'seller.html',{'sel':sel,'msg':msg})
    return render(request,'seller.html',{'sel':sel})

def product(request):
    prod=productform()
    if request.method=="POST":
        prod=productform(request.POST)
        if prod.is_valid():
            prname=prod.cleaned_data['Product_name']
            prprice=prod.cleaned_data['price']
            catid=prod.cleaned_data['category_ID']
            selid=prod.cleaned_data['Seller_ID']
            res=ProductTable(Product_name=prname,price=prprice,category_ID=catid,Seller_ID=selid)
            res.save()
            msg="product added"
        return render(request,'product.html',{'prod':prod,'msg':msg})
    return render(request,'product.html',{'prod':prod})

'''def register(request):
   form=createuserform()
   if request.method=="POST":
       form=createuserform(request.POST)
       if form.is_valid():
           form.save()
   return render(request,'register.html',{'form':form})'''

def register(request):
    refrm=registerform()
    if request.method=="POST":
        refrm=registerform(request.POST)
        if refrm.is_valid():
            nme=refrm.cleaned_data['name']
            uname=refrm.cleaned_data['username']
            dob=refrm.cleaned_data['date_of_birth']
            adr=refrm.cleaned_data['adress']
            ema=refrm.cleaned_data['email']
            ph=refrm.cleaned_data['phone_number']
            pwd=refrm.cleaned_data['password']
            uname_true=user.objects.filter(username=uname).exists()
            email_true=user.objects.filter(email=ema).exists()
            if uname_true or  email_true:
                already="Username or email already exists"
                return render(request,'register.html',{'refrm':refrm,'already':already})
            else:
                res=user(name=nme,username=uname,date_of_birth=dob,adress=adr,email=ema,phone_number=ph,password=pwd,)
                res.save()
                return redirect('eshopapp:login')   
    return render(request,'register.html',{'refrm':refrm})
def login(request):
    log=loginform()
    if request.method=="POST":
        log=loginform(request.POST)
        if log.is_valid():
            unme=log.cleaned_data['username']
            pwd=log.cleaned_data['password']
            login_true=user.objects.filter(username=unme,password=pwd).exists()
            login_truee=user.objects.filter(username=unme,password=pwd)
            print('login true is',login_truee)
            for lo in login_truee:
                print(lo) 
                print('name:',lo.name)
            if login_true:
                usrdata=user.objects.get(username=unme)
                print('userdata is:',usrdata,'usrdata object name',usrdata.name)
                request.session['userid']=usrdata.user_id
                return redirect('eshopapp:admino')
            else:
                error='incorrect username or password'
                return render(request,'login.html',{'error':error,'login':log})  
    return render(request,'login.html',{'login':log})  

def addcart(request,pid):
    pr=ProductTable.objects.get(Product_ID=pid)
    usr=user.objects.get(user_id=request.session['userid'])
    print(pr)
    qry=cart(Product_ID=pr,user_id=usr)
    
    qry_true=cart.objects.filter(Product_ID=pr,user_id=usr).exists()
    if qry_true:
        add="Already added"
        return render(request,'cartalreadyadd.html',{'add':add})
    else:        
        qry.save()
        return redirect('eshopapp:admino')
        
    
    #crt=cartform(instance=pr)
    return redirect('eshopapp:admino')

def dellogininfo(request):
    del request.session['username']
    request.session.flush()
    return redirect('eshopapp:login')

'''def buyprod(request):
    buy=buyprodform()
    pr=ProductTable.objects.all()

    return render(request,'buyprod.html',{'buy':buy,'pr':pr})'''

def cartdisplay(request):
    if 'userid' in request.session:
        cart_data=cart.objects.select_related('Product_ID').filter(user_id=request.session['userid']) #only filtering in products ordered each user
        pr=ProductTable.objects.all()
    return render(request,'addcart.html',{'cart_data':cart_data,'pr':pr})
def checkoutedit(request,pid):
    if 'userid' in request.session:
        
        ptab=ProductTable.objects.get(Product_ID=pid)
        usr=user.objects.get(user_id=request.session['userid'])
        qty=request.POST['price']
        for i in qty:
            qty_selected=i
        price=int(qty_selected)*ptab.price
        ord_date=date.today()
        exp_date=ord_date+timedelta(days=10)
        ord=orders(user_ID=usr,Product_ID=ptab,quantity=qty , TotalPrice=price,Order_date=ord_date,Expected_Delivery=exp_date)
        ordfm=orderform(instance=ord)
        ord.save()
        return render(request,'checkout.html',{'ord':ordfm})
    return render(request,'checkout.html')

eshoppieapp/templates/addcart.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">
    
    <link rel="stylesheet" href="{% static '/css/mystyle.css' %}">
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
</head>
<body id="bg" style=" background-image:url({%static '/image/background.jpg' %}); margin-top: 10px">
    <div class="row">
		<div class="col-lg-12">
			<div class="box-element">

				<a  class="btn btn-outline-dark" href="{% url 'eshopapp:admino' %}">&#x2190; Continue Shopping</a>

				<br>
				<br>
				<table class="table">
					<tr>
					
						<th>
							<a  style="float:right; margin:5px;" class="btn btn-success" href="#">Checkout</a>
						</th>
					</tr>
				</table>

			</div>

			<br>


			
			<div class="box-element">
				<div class="cart-row">
					
					<div style="flex:2"><strong>Item</strong></div>
					<div style="flex:1"><strong>Price</strong></div>
					<div style="flex:2"> <strong>Quantity</strong></div>
					

				</div>
				{% for i in cart_data %}
				<div class="cart-row">
					<div style="flex:2">{{i.Product_ID.Product_name}} </div>
					<div style="flex:2">{{i.Product_ID.price}} </div>
					<div style="flex:2"> 
						<form action="{% url 'eshopapp:checkout' i.Product_ID.Product_ID %}" method="post"> {% csrf_token %}
						<select name="price" required>
					
						 <option value=1> 1  </option> 
						 <option value=2> 2 </option> 
						 <option value=3> 3  </option> 
						 <option value=4> 4  </option> 
						 <option value=5> 5  </option> 
						 <option value=6> 6  </option> 
						 <option value=7> 7  </option> 
						 <option value=8> 8  </option> 
						 <option value=9> 9  </option> 
						 <option value=10> 10  </option> 
						</select>

					</div>
					
					<div style="flex:2"><input type="submit" value="Checkout" class="btn btn-success"> </div> </form>
				</div>
				{% endfor %}
			</div> 



		</div>
	</div>
    </table>
</body>

</html>

eshoppieapp/templates/admin.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

        
          
        <div class="row">
          {% for product in products %}
          <div class="col-lg-4">
            <img class="thumbnail" src="{{product.imageURL}}">
            <div class="box-element product">
              <h6><strong>{{product.name}}</strong></h6>
              <hr>
      <form action="{% url 'eshopapp:addcart' product.Product_ID %}" method="post">{% csrf_token %}
              <input type="submit" value="Add to Cart" class="btn btn-outline-secondary add-btn update-cart">{{add}}
            
              
              <h4 style="display: inline-block; float: right"><strong>${{product.price}}</strong></h4>
      
            </div>
          </div> </form>
          {% endfor %}
        </div> 
       
      
        {% endblock content %}        
 

eshoppieapp/templates/buyprod.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table border="1">
       <tr> <th>Product</th> 
        <th>Price</th> 
        <th>Add</th> </tr>
       {% for p in  pr %}

       <tr>
          <td>{{p.Product_name}}</td>  
          <td>{{p.price}}</td>  
          <td><a href="{% url 'eshopapp:addcart'  %}">Add to cart</a></td>  
       </tr>
       {% endfor %}
       
    </table>
  
</body>
</html>

eshoppieapp/templates/cartalreadyadd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{add}}</h1>
</body>
</html>

eshoppieapp/templates/category.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">
    
	<link rel="stylesheet" href="{% static '/css/mystyle.css' %}">
    </head>
<body id="bg" style=" background-image:url({%static '/image/background.jpg' %}); margin-top: 20px">
    <!--label for="category_name">Category name </label>
    <input type="text" id="category_name" value="#" name=" category_name"> <br> <br>
    <label for="category_description">Category description </label>
    <input type="text" id="category_description" value="#" name="category_description"-->
   <div class="container">
       <h1 style="text-align: center;color: cornflowerblue;text-decoration: underline;">Add Category</h1>
    <form action="{% url 'eshopapp:category' %}" method="POST">
        <table>
        {% csrf_token %}
        {{cat.as_table}}
        </table> <br>
        <input class="btn btn-success" type="submit" value="Add category" style="margin-left: 160px;">{{msg}}
    </form>
       </div>
</body>
</html>

eshoppieapp/templates/checkout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
 <link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">
    
 <link rel="stylesheet" href="{% static '/css/mystyle.css' %}">
</head>

<body id="bg" style=" background-image:url({%static '/image/background.jpg' %}); margin-top: 10px">
    <form action="" method="POST">
       
        {% csrf_token %}
       
        {% for o in ord %}  <table>
        <tr>
          <td> {{o.label}} 
           {{o}} </td>
        </tr>
        {% endfor %}
        </table>
        
        <input type="submit" value="Buy product" class="btn btn-primary btn-lg">
    </form>
</body>
</html> 

eshoppieapp/templates/index.html
<html>
    <head>

    </head>

    <body>
       <form method="POST" action="#">
           {% csrf_token %}
            {{ind.as_p}}
           <input type="submit" value="Login">

       </form> 
    </body>
    </html>

eshoppieapp/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
 <link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">
    
 <link rel="stylesheet" href="{% static '/css/mystyle.css' %}">
</head>
<body id="bg" style=" background-image:url({%static '/image/background.jpg' %}); margin-top: 18px;">
    <h1></h1>
    <div class="container">
    
    <form action="{% url 'eshopapp:login' %}" method="post">
        {% csrf_token %}
        <table class="table table-success table-striped">
        
        {{login.as_table}}
        
            </table>
         &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;
        &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;
         &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;
        &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;
         &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;
         &nbsp;&nbsp
        <input class="btn btn-success btn-lg" type="submit" value="login" style="margin-top: 8px;"> {{error}}
        <a class="btn btn-success btn-lg" style="margin-top: 8px;" href="{% url 'eshopapp:register' %}">Register</a>
        </form>
        
       
        
    </div>
</body>
</html>

eshoppieapp/templates/main.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Ecom</title>

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

</head>
<body>

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="#">E shoppie</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item active">
	        <a class="nav-link" href="{% url 'eshopapp:admino' %}">Home <span class="sr-only">(current)</span></a>
	      </li>
	      <li class="nav-item">
			  <a class="nav-link" href="{% url 'eshopapp:category' %}">Add category</a>
		  </li>
		  <li class="nav-item">
			<a class="nav-link" href="{% url 'eshopapp:seller' %}">Add seller</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="{% url 'eshopapp:product' %}">Add product</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="{% url 'eshopapp:register' %}">Register a user</a> 
		</li>
	    </ul>
	    <div class="form-inline my-2 my-lg-0">
	     	<a href="{% url 'eshopapp:login' %}" class="btn btn-warning">Logout</a>
	     	
	     	<a href="{% url  'eshopapp:cartdisplay' %}">
	    		<img  id="cart-icon" src="{% static 'image/cart.png' %}">
	    	</a>
	    	<p id="cart-total">{{cartItems}}</p>

	    </div>
	  </div>
	</nav>

     <div class="container">
            <br>
            {% block content %}


            {% endblock content %}
         </div>


	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

	
</body>
</html>

eshoppieapp/templates/product.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
 <link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">
    
 <link rel="stylesheet" href="{% static '/css/mystyle.css' %}">
</head>
<body id="bg" style=" background-image:url({%static '/image/background.jpg' %}); margin-top: 10px">
    <div class="container">
        <div class="jumbotron">
    <form action="{% url 'eshopapp:product' %}" method="POST" enctype="multipart/form-data">
        <table>
        {% csrf_token %}
        {{prod.label}}
        {{prod.label.category}}
       
        {{prod.as_table}}
            </table> <br>
        <input class="btn btn-success" type="submit" value="add product" style="margin-left: 100px"> {{msg}}

    </form>
        </div>
        </div>
</body>
</html>

eshoppieapp/templates/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
 <link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">
    
 <link rel="stylesheet" href="{% static '/css/mystyle.css' %}">
</head>
<body id="bg" style=" background-image:url({%static '/image/background.jpg' %}); margin-top: 10px">
    <div class="container">
    
    <form method="POST" action="{% url 'eshopapp:register' %}">
        <table>
        {% csrf_token %}
       <!--{{ usfm.as_p }} -->
      <!--- <label for="name">Name</label> <input type="text" name="name" id="name"> <br> <br>
       <label for="username">username</label> <input type="text" name="username"> <br> <br>
       <label for="date_of_birth">Date of birth</label> <input type="datetime-local" name="date_of_birth"> <br> <br>
       <label for="adress">Adress</label> <textarea name="adress" rows="10" cols="18"></textarea> <br> <br>
       <label for="email">Email</label> <input type="email" name="email" id="email"> <br> <br>
       <label for="phone_number">phone_number</label> <input type="text" name="phone_number" id="phone_number"> <br> <br>
       <label for="password">password</label> <input type="password" name="password" id="password"> <br> <br>
       <label for="confirm_password">confirm_password</label> <input type="password" name="confirm_password" id="confirm_password">
       <br> <br>-->
      
      {{refrm.as_table}}
     </table>
     &nbsp;  &nbsp; &nbsp;  &nbsp;&nbsp;  &nbsp; &nbsp;  &nbsp;&nbsp;  &nbsp; &nbsp;  &nbsp;
        &nbsp;  &nbsp; &nbsp;  &nbsp;&nbsp;  &nbsp; &nbsp;  &nbsp;&nbsp;  &nbsp; &nbsp;  &nbsp;
        &nbsp;  &nbsp; 
     <input class="btn btn-primary btn-lg" type="submit" value="register" style="margin-top: 8px;" >
     <a href="{% url 'eshopapp:login' %}" class="btn btn-primary btn-lg" style="margin-top: 8px;" >Login </a>
     <br><h4>{{already}} </h4>
    </form>
        
     
       
    </div>
      

   
</body>
</html>

eshoppieapp/templates/seller.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">
    
	<link rel="stylesheet" href="{% static '/css/mystyle.css' %}">
    </head>
<body id="bg" style=" background-image:url({%static '/image/background.jpg' %}); margin-top: 20px">
    <div class="container">
        <h1 style="text-align: center;color: cornflowerblue;text-decoration: underline;">Add seller</h1>
    <form action="#" method="POST">
        <table >
        {% csrf_token %}
        {{sel.as_table}}
        </table> <br>
        <input  class="btn btn-danger btn-lg" type="submit" value="add seller" style="margin-left: 90px;"> {{msg}}
    </form>
        </div>
</body>
</html>